apiVersion: apps/v1
kind: Deployment
metadata:
  name: daisy-deployment
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: daisy-container
        image: nginx
        ports:
        - containerPort: 80
      # volumes:
      # - name: config-map-volume
      #   configMap:
      #     name: daisy-exam8-config

