apiVersion: v1
kind: Pod
metadata:
  name: p3-daisy
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: ["/bin/sh"]
    args: ["-c","while true; do echo 'Hi I am from Main container' >> /var/log/index.html; sleep 5; done"]
    volumeMounts:
    - mountPath: /var/log
      name: test-vol
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: test-vol
  volumes:
  - name: test-vol
    emptyDir:
      sizeLimit: 500Mi


