apiVersion: v1
kind: Pod
metadata:
  name: p5-daisy
spec:
  containers:
  - name: busybox1
    image: busybox
    command: ["/bin/sh"]
    args: ["-c","ls; sleep 3600;"]
  - name: busybox2
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo Hello World; sleep 3600;"]
  - name: busybox3
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "echo this is the third container; sleep 3600"]

